version: "3.4"

networks:
  tradistonks-api:
    external: true
    name: tradistonks-api

services:
  tradistonks-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./components:/usr/src/app/components
      - ./pages:/usr/src/app/pages
      - ./public:/usr/src/app/public
      - ./styles:/usr/src/app/styles
      - ./utils:/usr/src/app/utils
    networks:
      - tradistonks-api
    ports:
      - 3080:3000
    env_file: .env
    environment:
      API_EXTERNAL_HOST: ${API_EXTERNAL_HOST}
      API_INTERNAL_HOST: ${API_INTERNAL_HOST}
      OAUTH2_LOCAL_URL: ${OAUTH2_LOCAL_URL}
      OAUTH2_LOCAL_CLIENT_ID: ${OAUTH2_LOCAL_CLIENT_ID}
      OAUTH2_LOCAL_REDIRECT_URL: ${OAUTH2_LOCAL_REDIRECT_URL}
      OAUTH2_PKCE_STATE: ${OAUTH2_PKCE_STATE}
