version: "3.4"

services:
  tradistonks-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./components:/usr/src/app/components
      - ./models:/usr/src/app/models
      - ./pages:/usr/src/app/pages
      - ./public:/usr/src/app/public
      - ./services:/usr/src/app/services
      - ./styles:/usr/src/app/styles
      - ./utils:/usr/src/app/utils
      - ./hooks:/usr/src/app/hooks
      - ./icons:/usr/src/app/icons
    ports:
      - 3080:3000
